<a href="https://colab.research.google.com/github/Varchala/NaturalLanguageProcessing_CSC8980/blob/main/HW2_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Varchaleswari Ganugapati**

**vganugapati1@student.gsu.edu**

**1.** Create a cosine similarity matrix for all of Shakespeare’s works found in the provided
file. This will result in a 42 by 42 matrix with the cosine similarity between each of his
works. In other words, calculate the document-wise cosine similarity between all of
Shakepeare’s works. (50 points). Use TF_IDF for this. Note, you can use the Cosine
Similarity function on scikit-learn or implement your own, but no other library/package is
allowed.

In [458]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import os

In [459]:
#Data preprocessing
path='/content/sample_data/shakp'
count=0
fileMatrix=[]
fileName=[]
with os.scandir(path) as files:
    for file in files:
        if file.name.endswith(".txt"):
            count +=1
            fileName.append(file.name)
            with open(path+"/"+file.name) as openfile:
              fileMatrix.append(openfile.read())
    print(count)

42


In [460]:
# print(fileMatrix[1])
print(fileName)

['the-two-noble-kinsmen_TXT_FolgerShakespeare.txt', 'coriolanus_TXT_FolgerShakespeare.txt', 'henry-iv-part-1_TXT_FolgerShakespeare.txt', 'king-john_TXT_FolgerShakespeare.txt', 'king-lear_TXT_FolgerShakespeare.txt', 'henry-v_TXT_FolgerShakespeare.txt', 'henry-vi-part-1_TXT_FolgerShakespeare.txt', 'a-midsummer-nights-dream_TXT_FolgerShakespeare.txt', 'pericles_TXT_FolgerShakespeare.txt', 'the-comedy-of-errors_TXT_FolgerShakespeare.txt', 'othello_TXT_FolgerShakespeare.txt', 'the-merry-wives-of-windsor_TXT_FolgerShakespeare.txt', 'venus-and-adonis_TXT_FolgerShakespeare.txt', 'the-phoenix-and-turtle_TXT_FolgerShakespeare.txt', 'troilus-and-cressida_TXT_FolgerShakespeare.txt', 'the-merchant-of-venice_TXT_FolgerShakespeare.txt', 'henry-iv-part-2_TXT_FolgerShakespeare.txt', 'alls-well-that-ends-well_TXT_FolgerShakespeare.txt', 'shakespeares-sonnets_TXT_FolgerShakespeare.txt', 'antony-and-cleopatra_TXT_FolgerShakespeare.txt', 'the-winters-tale_TXT_FolgerShakespeare.txt', 'measure-for-measure_TX

In [461]:


#TfidfVectorizer object
vectorizer = TfidfVectorizer()

# matrix of word vectors
tfidf_matrix = vectorizer.fit_transform(fileMatrix)

#shape of tfidf_matrix
print(tfidf_matrix.shape)

(42, 24618)


In [462]:
tfidf_tokens = vectorizer.get_feature_names()
print(tfidf_tokens[20:40])
print(len(tfidf_tokens))

['118', '119', '12', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '13', '130', '131', '132', '133', '134', '135']
24618


In [463]:

# compute and print the cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)


In [464]:
print(cosine_sim.shape)
print(cosine_sim)

(42, 42)
[[1.         0.59813572 0.65459176 ... 0.52515851 0.57395169 0.69694474]
 [0.59813572 1.         0.66801609 ... 0.5890345  0.59258345 0.71771293]
 [0.65459176 0.66801609 1.         ... 0.59895863 0.66716633 0.79038899]
 ...
 [0.52515851 0.5890345  0.59895863 ... 1.         0.52277672 0.62033426]
 [0.57395169 0.59258345 0.66716633 ... 0.52277672 1.         0.70530628]
 [0.69694474 0.71771293 0.79038899 ... 0.62033426 0.70530628 1.        ]]


**2.** Write a function that takes the previous matrix and a number n as parameters (nothing
else will be accepted) and return the top n similar works. Use the function to output the
top 10 similar works. (30 points).


In [465]:
# df = pd.DataFrame(cosine_sim,columns=fileName,index=fileName)
# df.stack().nlargest(20)

In [466]:
def find_similar_docs(matrix,n):
  docs=[]
  np.fill_diagonal(matrix, 0)
  idx = np.argsort(matrix.ravel())[:-n-1:-1]
  similar = np.column_stack(np.unravel_index(idx, matrix.shape))
  for i in range(n):
    docs.append(fileName[similar[i][0]])
  return docs
out = find_similar_docs(cosine_sim,10)
print(out)
print("The list is:")
for i in out:
  print(i)

['venus-and-adonis_TXT_FolgerShakespeare.txt', 'lucrece_TXT_FolgerShakespeare.txt', 'henry-iv-part-2_TXT_FolgerShakespeare.txt', 'henry-iv-part-1_TXT_FolgerShakespeare.txt', 'shakespeares-sonnets_TXT_FolgerShakespeare.txt', 'lucrece_TXT_FolgerShakespeare.txt', 'henry-vi-part-2_TXT_FolgerShakespeare.txt', 'henry-vi-part-1_TXT_FolgerShakespeare.txt', 'richard-ii_TXT_FolgerShakespeare.txt', 'richard-iii_TXT_FolgerShakespeare.txt']
The list is:
venus-and-adonis_TXT_FolgerShakespeare.txt
lucrece_TXT_FolgerShakespeare.txt
henry-iv-part-2_TXT_FolgerShakespeare.txt
henry-iv-part-1_TXT_FolgerShakespeare.txt
shakespeares-sonnets_TXT_FolgerShakespeare.txt
lucrece_TXT_FolgerShakespeare.txt
henry-vi-part-2_TXT_FolgerShakespeare.txt
henry-vi-part-1_TXT_FolgerShakespeare.txt
richard-ii_TXT_FolgerShakespeare.txt
richard-iii_TXT_FolgerShakespeare.txt


**As the similarity is between pairs of docs, I wrote one more function  that returns the top k "pairs" of docs rather than just the docs**

In [467]:
def find_similar_docs(matrix,n):
  docs=[]
  final_doc=[]
  np.fill_diagonal(matrix, 0)
  n=n*2
  idx = np.argsort(matrix.ravel())[:-n-1:-1]
  similar = np.column_stack(np.unravel_index(idx, matrix.shape))
  for i in range(n):
    docs.append(fileName[similar[i][0]])
  for i in range(0,len(docs)-1,2):
    final_doc.append(docs[i]+" && "+docs[i+1])
  return final_doc
out = find_similar_docs(cosine_sim,10)
# print(out)
print("The doc pairs are:")
for i in out:
  print(i)

The doc pairs are:
venus-and-adonis_TXT_FolgerShakespeare.txt && lucrece_TXT_FolgerShakespeare.txt
henry-iv-part-2_TXT_FolgerShakespeare.txt && henry-iv-part-1_TXT_FolgerShakespeare.txt
shakespeares-sonnets_TXT_FolgerShakespeare.txt && lucrece_TXT_FolgerShakespeare.txt
henry-vi-part-2_TXT_FolgerShakespeare.txt && henry-vi-part-1_TXT_FolgerShakespeare.txt
richard-ii_TXT_FolgerShakespeare.txt && richard-iii_TXT_FolgerShakespeare.txt
venus-and-adonis_TXT_FolgerShakespeare.txt && shakespeares-sonnets_TXT_FolgerShakespeare.txt
henry-viii_TXT_FolgerShakespeare.txt && henry-v_TXT_FolgerShakespeare.txt
henry-vi-part-3_TXT_FolgerShakespeare.txt && henry-vi-part-2_TXT_FolgerShakespeare.txt
henry-vi-part-2_TXT_FolgerShakespeare.txt && richard-ii_TXT_FolgerShakespeare.txt
king-john_TXT_FolgerShakespeare.txt && henry-v_TXT_FolgerShakespeare.txt


**The same code when the function prints the list values rather than returning them**

In [468]:
def find_similar_docs(matrix,n):
  docs=[]
  final_doc=[]
  np.fill_diagonal(matrix, 0)
  n=n*2
  idx = np.argsort(matrix.ravel())[:-n-1:-1]
  similar = np.column_stack(np.unravel_index(idx, matrix.shape))
  for i in range(n):
    docs.append(fileName[similar[i][0]])
  for i in range(0,len(docs)-1,2):
    final_doc.append(docs[i]+" && "+docs[i+1])
  print("The list is:")
  for i in final_doc:
    print(i)
find_similar_docs(cosine_sim,10)
# print(out)


The list is:
venus-and-adonis_TXT_FolgerShakespeare.txt && lucrece_TXT_FolgerShakespeare.txt
henry-iv-part-2_TXT_FolgerShakespeare.txt && henry-iv-part-1_TXT_FolgerShakespeare.txt
shakespeares-sonnets_TXT_FolgerShakespeare.txt && lucrece_TXT_FolgerShakespeare.txt
henry-vi-part-2_TXT_FolgerShakespeare.txt && henry-vi-part-1_TXT_FolgerShakespeare.txt
richard-ii_TXT_FolgerShakespeare.txt && richard-iii_TXT_FolgerShakespeare.txt
venus-and-adonis_TXT_FolgerShakespeare.txt && shakespeares-sonnets_TXT_FolgerShakespeare.txt
henry-viii_TXT_FolgerShakespeare.txt && henry-v_TXT_FolgerShakespeare.txt
henry-vi-part-3_TXT_FolgerShakespeare.txt && henry-vi-part-2_TXT_FolgerShakespeare.txt
henry-vi-part-2_TXT_FolgerShakespeare.txt && richard-ii_TXT_FolgerShakespeare.txt
king-john_TXT_FolgerShakespeare.txt && henry-v_TXT_FolgerShakespeare.txt


In [469]:
# # fileName[12 32]
# out[5][0]

**3.** Using the code from the Language Models II class, train two simple language models
using all of the files (together) in shakespeares-works_TXT_FolgerShakespeare.zip. One
model should be trained using bigrams, the other using trigrams. (40 points).


In [470]:
# Preprocess data
import nltk, re
from nltk import word_tokenize, sent_tokenize
from nltk import bigrams, trigrams
from collections import Counter, defaultdict
nltk.download('punkt')
import string

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [471]:
print(len(fileMatrix))

42


In [472]:
string.punctuation = string.punctuation.replace('.', '')
string.punctuation = string.punctuation.replace(',', '')
print(string.punctuation)
data = ""
count=0
for doc in fileMatrix:
  # print(doc[0:20])
  
  data += "".join([char for char in doc if char not in string.punctuation])
  # print(data[-8:-1])
  # print("\n")
  count +=1
data = data.replace("\n", " ")
print(count)

!"#$%&'()*+-/:;<=>?@[\]^_`{|}~
42


In [473]:
data = data.lower()
data[20:20]

''

In [474]:
sents = nltk.sent_tokenize(data)
print("Sentences Count", len(sents)) 
words = nltk.word_tokenize(data)
print("Tokens Count", len(words)) 
uq_words = set(words)
print("Unique Words Count", len(uq_words))

Sentences Count 61495
Tokens Count 1117742
Unique Words Count 29965


In [475]:
corpus=[]
for sentence in sents:
  s = []
  wr = nltk.word_tokenize(sentence)
  for w in wr:
    s.append(w)
  corpus.append(s)


In [476]:
len(corpus)

61495

In [477]:
#Training Trigram models
# Create a placeholder for model
model_tri = defaultdict(lambda: defaultdict(lambda: 0))

# Count frequency of co-occurence  
for sentence in corpus:
    # print(sentence)
    # break;
    # list(nltk.ngrams(sent, 2))
    for w1, w2, w3 in trigrams(sentence, pad_right=True, pad_left=True):
        model_tri[(w1, w2)][w3] += 1
 
# Let's transform the counts to probabilities
for w1_w2 in model_tri:
    total_count = float(sum(model_tri[w1_w2].values()))
    for w3 in model_tri[w1_w2]:
        model_tri[w1_w2][w3] /= total_count

In [478]:

dict(model_tri["the","court"])

{',': 0.16346153846153846,
 '.': 0.22115384615384615,
 'a': 0.009615384615384616,
 'admired': 0.009615384615384616,
 'and': 0.0673076923076923,
 'are': 0.009615384615384616,
 'at': 0.009615384615384616,
 'awards': 0.019230769230769232,
 'ay': 0.009615384615384616,
 'but': 0.009615384615384616,
 'can': 0.009615384615384616,
 'clean': 0.009615384615384616,
 'cupboard': 0.009615384615384616,
 'fool': 0.009615384615384616,
 'for': 0.009615384615384616,
 'gate': 0.019230769230769232,
 'here': 0.009615384615384616,
 'how': 0.009615384615384616,
 'hurry': 0.009615384615384616,
 'ill': 0.009615384615384616,
 'in': 0.028846153846153848,
 'is': 0.009615384615384616,
 'lay': 0.009615384615384616,
 'let': 0.009615384615384616,
 'may': 0.009615384615384616,
 'myself': 0.009615384615384616,
 'of': 0.1346153846153846,
 'portia': 0.009615384615384616,
 'receives': 0.009615384615384616,
 'shall': 0.009615384615384616,
 'sound': 0.009615384615384616,
 'third': 0.009615384615384616,
 'to': 0.028846153846

In [479]:
dict(model_tri["skillful","enough"])

{'to': 1.0}

In [480]:
#Training Bigram models
# Create a placeholder for model
model_bi = defaultdict(lambda: defaultdict(lambda: 0))

# Count frequency of co-occurence  
for sentence in corpus:
    # print(sentence)
    # break;
    # list(nltk.ngrams(sent, 2))
    for w1, w2 in bigrams(sentence, pad_right=True, pad_left=True):
        model_bi[w1][w2] += 1
 
# Let's transform the counts to probabilities
for w1 in model_bi:
    total_count = float(sum(model_bi[w1].values()))
    for w2 in model_bi[w1]:
        model_bi[w1][w2] /= total_count

In [481]:
dict(model_bi["skillful"])

{',': 0.2857142857142857,
 'conserved': 0.14285714285714285,
 'enough': 0.14285714285714285,
 'painting': 0.14285714285714285,
 'pilots': 0.14285714285714285,
 'shepherd': 0.14285714285714285}

**4.** Write a function that takes the following three parameters: model, list of start words,
number of sentences to generate. This function should return the sentences generated
as a list. DO NOT print anything to the screen from within the function. Use this function
to generate 10 sentences with the bigram model from the previous question, and 5
sentences with the trigram model from the previous question. (30 points)

In [482]:
import random

def sent_generator(model,textt,n):
# starting words
# text = ["today", "the"]
  text = textt.copy()
  final_text=[]
  for i in range(n):
    sentence_finished = False
    complete_text = ""
    while not sentence_finished:
      # select a random probability threshold  
      r = random.random()
      accumulator = .0
      if(len(text)>1 and len(list(model[tuple(text[-2:])].keys()))>0):
        # if(len(list(model[tuple(text[-2:])].keys()))>0):
          for word in model[tuple(text[-2:])].keys():

              accumulator += model[tuple(text[-2:])][word]
              # select words that are above the probability threshold
              if accumulator >= r:
                  text.append(word)
                  break
          if text[-2:] == [None, None]:
              # print(text[-2:])
              sentence_finished = True
      elif(len(text)>0 and len(list(model[text[-1]].keys()))>0):
          for word in model[text[-1]].keys():

              accumulator += model[text[-1]][word]
              # select words that are above the probability threshold
              if accumulator >= r:
                  text.append(word)
                  break

          if text[-1] == None:
              sentence_finished = True
      elif(len(text)>0 and len(list(model[text[-1]].keys()))==0 and len(list(model[tuple(text[-2:])].keys()))==0):
        sentence_finished = True
      elif(len(text)==0):
        text = ["Invalid text length for start words"]
        sentence_finished = True

    complete_text = ' '.join([t for t in text if t])

    final_text.append(complete_text)
    text = textt.copy()
  return final_text

In [483]:
output = sent_generator(model_bi,['are','you','lost'],10)
print(output)
print(len(output))
output = sent_generator(model_tri,['are','you','lost'],5)
print(output)
print(len(output))

['are you lost .', 'are you lost best pound a boy , above .', 'are you lost and dissolutely .', 'are you lost their reasons are they him for buckingham ay , this twofold marriagetwixt my long .', 'are you lost the hated thee , this charge .', 'are you lost , descended into a creature , rather blamed shall acquittance seal with foul mouth .', 'are you lost .', 'are you lost cousins , that now reign as i am thankful that you mean obsequies that with a means the lady grey and low and here to the net nor the world but ill attach the death can be flattered no more comingon disposition , he done in transformation , in that i fear of my consent .', 'are you lost in your excellent motion turn his but the worthies costard i pray hortensio , sir , that father was troubled with a first friend , tis true delight to the land indeed , with my bedfellow .', 'are you lost when i mean piratesand then , goodman puff of either presuming them .']
10
['are you lost a dearer father in my life , that have th

In [484]:
len(list(model_bi['thy'].keys()))

1645

In [485]:
model_bi['am'].keys()

dict_keys(['sure', '.', 'going', 'entreating', 'i', 'the', 'none', 'not', 'given', 'delivered', 'your', 'sufficient', 'wondrous', 'as', 'ready', 'resolved', 'happy', 'base', 'proud', 'desperate', 'then', 'in', 'persuaded', 'a', 'moped', 'glad', 'gladder', 'very', 'spared', 'friends', 'well', 'an', 'indifferent', 'i.', 'perfect', 'palamon', 'and', 'set', 'deaf', 'nothing', 'sotted', 'to', ',', 'humbled', 'bridehabited', 'guiltless', 'of', 'much', 'content', 'extinct', 'like', 'most', 'now', 'cruel', 'constant.titus', 'bound', 'weary', 'his', 'attended', 'known', 'light', 'half', 'out', 'so', 'lacked', 'forth', 'joyful', 'longer', 'prepared', 'one', 'bigger', 'hushed', 'here', 'returned', 'struck', 'whipped', 'stung', 'joined', 'accursed', 'bewitched', 'ahorseback', 'sworn', 'no', 'king', 'eight', 'afraid', 'schooled', 'too', 'ignorance', 'doubtless', 'charged', 'withered', 'pacified', 'good', 'heinously', 'on', 'truly', 'thy', 'dubbed', 'sick', 'perplexed', 'with', 'burned', 'almost', '

In [486]:
if(model_tri[tuple(['i','am'])].keys()!=[]):
  print("jj")

jj


**Bonus** (20 points): Using the same methodology from questions 1 and 2, create a
similarity matrix between the 20 newsgroups corpus. And find the top 5 similar
newsgroups.

In [487]:
from sklearn.datasets import fetch_20newsgroups

data = fetch_20newsgroups()
data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [488]:
data.target_names[1]
# for i in data.target_names:
#   print(i)

'comp.graphics'

In [489]:
final_data = []
text_data = ""
for i in data.target_names:
  train = fetch_20newsgroups(subset='train', categories=[i])
  # test = fetch_20newsgroups(subset='test', categories=categories)
  for j in train.data:
    text_data += " "+j
  final_data.append(text_data)


In [490]:
len(final_data)

20

In [491]:
#TfidfVectorizer object
vectorizer = TfidfVectorizer()

# matrix of word vectors
tfidf_matrix = vectorizer.fit_transform(final_data)

#shape of tfidf_matrix
print(tfidf_matrix.shape)

(20, 130107)


In [492]:
tfidf_tokens = vectorizer.get_feature_names()
print(tfidf_tokens[10000:10005])
print(len(tfidf_tokens))

['26m', '26n', '26q', '26ql24do2', '26qz_l']
130107


In [493]:
# compute and print the cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [494]:
print(cosine_sim.shape)
print(cosine_sim)

(20, 20)
[[1.         0.99014536 0.38420893 0.46601216 0.53228932 0.62105783
  0.64370599 0.69568878 0.73208498 0.76417605 0.79571894 0.83594542
  0.8504816  0.86976691 0.88353065 0.90408429 0.91499735 0.92675252
  0.93401827 0.93858153]
 [0.99014536 1.         0.3900986  0.47448653 0.54268787 0.6342324
  0.65882102 0.71116798 0.74805383 0.78006296 0.81171952 0.85180951
  0.86670461 0.88565865 0.89964864 0.91797864 0.92823376 0.93895093
  0.94545396 0.94935981]
 [0.38420893 0.3900986  1.         0.99499454 0.98333801 0.95549826
  0.94469761 0.91811517 0.89426445 0.8698225  0.83920372 0.79662421
  0.7774654  0.75286838 0.72984299 0.70087402 0.67936352 0.65085721
  0.63362786 0.62368582]
 [0.46601216 0.47448653 0.99499454 1.         0.99645716 0.97963774
  0.97210509 0.95229565 0.93347091 0.91345498 0.88760046 0.85097773
  0.83430203 0.81256299 0.79196804 0.76575067 0.74615537 0.7198376
  0.7039312  0.69471071]
 [0.53228932 0.54268787 0.98333801 0.99645716 1.         0.99266725
  0.98794

In [495]:
def find_similar_docs(matrix,n):
  docs=[]
  final_doc=[]
  np.fill_diagonal(matrix, 0)
  n=n*2
  idx = np.argsort(matrix.ravel())[:-n-1:-1]
  similar = np.column_stack(np.unravel_index(idx, matrix.shape))
  for i in range(n):
    docs.append(data.target_names[similar[i][0]])
  for i in range(0,len(docs)-1,2):
    final_doc.append(docs[i]+" && "+docs[i+1])
  print("The newsgroup pairs are:")
  for i in final_doc:
    print(i)
find_similar_docs(cosine_sim,5)
# print(out)


The newsgroup pairs are:
talk.politics.misc && talk.religion.misc
talk.politics.misc && talk.politics.mideast
sci.crypt && sci.electronics
soc.religion.christian && talk.politics.guns
sci.space && sci.med


In [496]:
def find_similar_docs(matrix,n):
  docs=[]
  np.fill_diagonal(matrix, 0)
  idx = np.argsort(matrix.ravel())[:-n-1:-1]
  similar = np.column_stack(np.unravel_index(idx, matrix.shape))
  for i in range(n):
    docs.append(data.target_names[similar[i][0]])
  return docs
out = find_similar_docs(cosine_sim,5)
print(out)
print("The list is:")
for i in out:
  print(i)

['talk.politics.misc', 'talk.religion.misc', 'talk.politics.misc', 'talk.politics.mideast', 'sci.crypt']
The list is:
talk.politics.misc
talk.religion.misc
talk.politics.misc
talk.politics.mideast
sci.crypt
